### ISSUE TITLE
Docker load balancer

### ISSUE THREAD

**Issue by brianquimio** [brianquimio/cs373-idb#21]

**Comment by shperl** [comment]
Tasks:
- lb directory needs to be created
- Dockerfile needs to be created
- docker-compose.yml needs to be modified to support multiple images

LOE: 5 hours

**Comment by shperl** [comment]
have this working on my iss21 branch. Will be merging to dev and pushing to dev tonight.

**Comment by shperl** [comment]
This is also a precursor to having the DB up and running.

**Comment by shperl** [comment]
Fixed -- also added DB image.
