### ISSUE TITLE
Add state parks to data model.

### ISSUE THREAD

**Issue by shperl** [brianquimio/cs373-idb#23]
- Find an API or static data set that has a common attribute with our current model.
- If it is via a rest API, create a python wrapper for accessing the data (app/static/other/locations.py for reference).
- Update the UML diagrams to reflect the new attributes.
- Incorporate the new data elements into the existing models.py file.
- Document the expanded data set in the Wiki and be sure to include the data source.

**Comment by shperl** [comment]
Hey, @adamalloy. I assigned this ticket to you as your were working on it this evening. Please review the locations.py and stats.py files that can be found in the app/static/other folder on the repo for a standard template for pulling down data via an API. It would be nice to create consistency between the two (creating a class for the pull, then creating methods for accessing functions).

**Comment by adamalloy** [comment]
Not quite ready to close this issue because I still need to implement parks around cities. For state parks, all these issue have been addressed: parks.py file, updated api, updated models, updated uml, updated wiki.

**Comment by shperl** [comment]
@adamalloy -- I noticed you added "park_name" to the state class. I don't think this will work well for us given the structure of our database. my recommendation would be to add a new class for "parks" that has foreign keys for any of the trulia classes that has a relation. This means we would need to create a separate model in the models.py file.
